### ISSUE TITLE
PHP Notice: Undefined index: autoRefresh 

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon-widget-engine-status#8]
Hello,
Every time this widget is shown i got this in the Apache log :
Centreon 2.7.8

PHP Notice: Undefined index: autoRefresh in /usr/share/centreon/www/widgets/engine-status/index.php on line 73,

Every time this widget is shown and there is no such property in the widgets

Regards.

**Comment by sc979** [comment]
Hi @BenoitPoulet ,
The refresh has been fixed at last here : https://github.com/centreon/centreon-widget-engine-status/pull/27
Best Regards
sc979
